import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlarmClock,
  AppWindow,
  CalendarClock,
  Clock,
  AtSign,
  Bell,
  Bot,
  CalendarDays,
  CircleGauge,
  Clapperboard,
  Cloud,
  CloudUpload,
  Cog,
  Download,
  EyeOff,
  FileArchive,
  FileAudio,
  FileClock,
  FileText,
  FileType2,
  Folder,
  FolderTree,
  Forward,
  Gauge,
  Globe,
  HardDrive,
  Hash,
  Image,
  KeyRound,
  Languages,
  Layers,
  Link2,
  ListOrdered,
  Lock,
  MessageSquareText,
  Mic,
  MonitorCog,
  Network,
  Palette,
  Plug,
  Power,
  Repeat,
  Route,
  ScanSearch,
  Server,
  Shield,
  SlidersHorizontal,
  Sparkles,
  SplitSquareHorizontal,
  Terminal,
  Timer,
  Trash2,
  User,
  Users,
  Video,
  Wifi,
  Zap,
} from "lucide-react";

export type PageId =
  | "dashboard"
  | "tasks"
  | "download"
  | "chats"
  | "network"
  | "upload"
  | "logs"
  | "settings"
  | "about";

export type FieldType =
  | "switch"
  | "number"
  | "text"
  | "password"
  | "select"
  | "segmented"
  | "path"
  | "file"
  | "tags"
  | "member"
  | "ordered"
  | "optional-switch"
  | "time";

export interface Option {
  label: string;
  value: string | number;
}

export interface SettingDef {
  id: string;
  page: PageId;
  tab: string;
  section: string;
  title: string;
  desc: string;
  icon: LucideIcon;
  /** Key path inside config.yaml, or inside desktop settings when `desktop`. */
  path: string[];
  type: FieldType;
  desktop?: boolean;
  defaultValue?: unknown;
  unit?: string;
  min?: number;
  max?: number;
  step?: number;
  width?: number;
  placeholder?: string;
  options?: Option[];
  /** For `member`: the list value this switch toggles. */
  member?: string;
  /** For `optional-switch`: the value written when switched on. */
  enableValue?: unknown;
  keywords?: string;
  /** Hide unless the given config path is truthy. */
  showIf?: string[];
}

export interface SectionDef {
  id: string;
  title: string;
  icon: LucideIcon;
  desc?: string;
}

export interface TabDef {
  id: string;
  label: string;
}

export interface PageDef {
  id: PageId;
  title: string;
  icon: LucideIcon;
  tabs: TabDef[];
}

export const PAGES: PageDef[] = [
  { id: "dashboard", title: "仪表盘", icon: Activity, tabs: [{ id: "live", label: "实时" }, { id: "stats", label: "统计" }] },
  {
    id: "tasks",
    title: "任务",
    icon: ListOrdered,
    tabs: [
      { id: "active", label: "进行中" },
      { id: "new", label: "新建任务" },
      { id: "pending", label: "待恢复" },
      { id: "history", label: "已结束" },
    ],
  },
  {
    id: "download",
    title: "下载",
    icon: Download,
    tabs: [
      { id: "media", label: "内容类型" },
      { id: "storage", label: "保存位置" },
      { id: "performance", label: "性能与重试" },
    ],
  },
  { id: "chats", title: "频道", icon: Users, tabs: [{ id: "list", label: "下载频道" }, { id: "ads", label: "广告过滤" }] },
  {
    id: "network",
    title: "网络",
    icon: Globe,
    tabs: [
      { id: "account", label: "账号" },
      { id: "proxy", label: "代理" },
      { id: "clash", label: "Clash 优化" },
    ],
  },
  { id: "upload", title: "上传", icon: CloudUpload, tabs: [{ id: "drive", label: "网盘上传" }, { id: "forward", label: "转发" }] },
  { id: "logs", title: "日志", icon: Terminal, tabs: [{ id: "live", label: "实时输出" }, { id: "file", label: "日志文件" }] },
  {
    id: "settings",
    title: "设置",
    icon: Cog,
    tabs: [
      { id: "general", label: "通用" },
      { id: "engine", label: "引擎" },
      { id: "data", label: "数据" },
      { id: "advanced", label: "高级" },
    ],
  },
  { id: "about", title: "关于", icon: Sparkles, tabs: [] },
];

export const SECTIONS: Record<string, SectionDef> = {
  media: { id: "media", title: "媒体类型", icon: Layers },
  formats: { id: "formats", title: "文件格式", icon: FileType2 },
  location: { id: "location", title: "保存路径", icon: Folder },
  naming: { id: "naming", title: "文件命名", icon: FileText },
  concurrency: { id: "concurrency", title: "并发", icon: Gauge },
  retry: { id: "retry", title: "超时与重试", icon: Timer },
  telegram: { id: "telegram", title: "Telegram API", icon: KeyRound },
  bot: { id: "bot", title: "机器人", icon: Bot },
  proxy: { id: "proxy", title: "代理服务器", icon: Route },
  clash: { id: "clash", title: "低速自动切换节点", icon: Zap },
  drive: { id: "drive", title: "网盘上传", icon: Cloud },
  forward: { id: "forward", title: "转发", icon: Forward },
  appearance: { id: "appearance", title: "外观与窗口", icon: Palette },
  startup: { id: "startup", title: "启动", icon: Power },
  notify: { id: "notify", title: "通知", icon: Bell },
  guard: { id: "guard", title: "下载计划与保护", icon: CalendarClock },
  engineRuntime: { id: "engineRuntime", title: "引擎程序", icon: MonitorCog },
  engineLog: { id: "engineLog", title: "日志", icon: FileClock },
  web: { id: "web", title: "Web 管理页面", icon: Server },
};

const mediaSwitch = (member: string, title: string, desc: string, icon: LucideIcon): SettingDef => ({
  id: `media_types.${member}`,
  page: "download",
  tab: "media",
  section: "media",
  title,
  desc,
  icon,
  path: ["media_types"],
  type: "member",
  member,
});

export const SETTINGS: SettingDef[] = [
  // ------------------------------------------------------------ download / media
  mediaSwitch("video", "视频", "关闭后，频道中的视频不会被下载。", Video),
  mediaSwitch("photo", "图片", "关闭后，频道中的图片不会被下载。", Image),
  mediaSwitch("document", "文档", "以文件形式发送的内容，包括压缩包、PDF、原画质图片与视频。", FileArchive),
  mediaSwitch("audio", "音频", "关闭后，音乐等音频文件不会被下载。", FileAudio),
  mediaSwitch("voice", "语音消息", "关闭后，语音消息不会被下载。", Mic),
  mediaSwitch("video_note", "视频消息", "圆形的视频消息。", Clapperboard),
  mediaSwitch("animation", "动图", "GIF 等动画。", Sparkles),
  {
    id: "enable_download_txt",
    page: "download",
    tab: "media",
    section: "media",
    title: "保存文字消息",
    desc: "没有媒体的纯文字消息也会保存为 .txt 文件。",
    icon: MessageSquareText,
    path: ["enable_download_txt"],
    type: "switch",
    defaultValue: false,
  },
  {
    id: "file_formats.video",
    page: "download",
    tab: "media",
    section: "formats",
    title: "视频格式",
    desc: "只下载这些扩展名的视频，填写 all 表示全部。",
    icon: Video,
    path: ["file_formats", "video"],
    type: "tags",
    placeholder: "mp4、mkv…",
    defaultValue: ["all"],
  },
  {
    id: "file_formats.document",
    page: "download",
    tab: "media",
    section: "formats",
    title: "文档格式",
    desc: "只下载这些扩展名的文档，如 pdf、zip；all 表示全部。",
    icon: FileArchive,
    path: ["file_formats", "document"],
    type: "tags",
    placeholder: "pdf、zip…",
    defaultValue: ["all"],
  },
  {
    id: "file_formats.audio",
    page: "download",
    tab: "media",
    section: "formats",
    title: "音频格式",
    desc: "只下载这些扩展名的音频，如 mp3、flac；all 表示全部。",
    icon: FileAudio,
    path: ["file_formats", "audio"],
    type: "tags",
    placeholder: "mp3、flac…",
    defaultValue: ["all"],
  },

  // ------------------------------------------------------------ download / storage
  {
    id: "save_path",
    page: "download",
    tab: "storage",
    section: "location",
    title: "下载目录",
    desc: "所有文件保存在此目录下；相对路径以工作目录为基准。",
    icon: HardDrive,
    path: ["save_path"],
    type: "path",
    keywords: "save_path 保存 目录",
  },
  {
    id: "file_path_prefix",
    page: "download",
    tab: "storage",
    section: "location",
    title: "子目录结构",
    desc: "按顺序生成子目录，例如 频道名称 / 2026_09。全部取消则直接存放在下载目录。",
    icon: FolderTree,
    path: ["file_path_prefix"],
    type: "ordered",
    options: [
      { label: "频道名称", value: "chat_title" },
      { label: "消息日期", value: "media_datetime" },
      { label: "媒体类型", value: "media_type" },
    ],
  },
  {
    id: "date_format",
    page: "download",
    tab: "storage",
    section: "location",
    title: "日期目录格式",
    desc: "“消息日期”子目录的命名方式，使用 Python strftime 格式。",
    icon: CalendarDays,
    path: ["date_format"],
    type: "select",
    defaultValue: "%Y_%m",
    options: [
      { label: "2026_09（按月）", value: "%Y_%m" },
      { label: "2026-09（按月）", value: "%Y-%m" },
      { label: "2026（按年）", value: "%Y" },
      { label: "2026_09_26（按天）", value: "%Y_%m_%d" },
      { label: "2026-09-26（按天）", value: "%Y-%m-%d" },
    ],
  },
  {
    id: "file_name_prefix",
    page: "download",
    tab: "storage",
    section: "naming",
    title: "文件名组成",
    desc: "按顺序拼接文件名，例如 18234 - 原文件名.mp4。",
    icon: ListOrdered,
    path: ["file_name_prefix"],
    type: "ordered",
    options: [
      { label: "消息 ID", value: "message_id" },
      { label: "原文件名", value: "file_name" },
      { label: "消息标题", value: "caption" },
    ],
  },
  {
    id: "file_name_prefix_split",
    page: "download",
    tab: "storage",
    section: "naming",
    title: "分隔符",
    desc: "文件名各部分之间的连接符。",
    icon: SplitSquareHorizontal,
    path: ["file_name_prefix_split"],
    type: "text",
    width: 120,
    defaultValue: " - ",
  },
  {
    id: "hide_file_name",
    page: "download",
    tab: "storage",
    section: "naming",
    title: "隐藏文件名",
    desc: "日志、机器人消息与 Web 页面中用 **** 代替文件名。",
    icon: EyeOff,
    path: ["hide_file_name"],
    type: "switch",
    defaultValue: false,
  },

  // ------------------------------------------------------------ download / performance
  {
    id: "max_download_task",
    page: "download",
    tab: "performance",
    section: "concurrency",
    title: "同时下载数",
    desc: "同时进行的媒体下载数量。过高容易触发 Telegram 限流。",
    icon: Layers,
    path: ["max_download_task"],
    type: "number",
    min: 1,
    max: 50,
    defaultValue: 5,
    unit: "个",
  },
  {
    id: "download_threads",
    page: "download",
    tab: "performance",
    section: "concurrency",
    title: "单文件并行分片",
    desc: "每个文件同时请求的 1 MB 分片数，用来抵消代理线路的延迟。设为 1 且连接数为 1 时使用原来的逐片下载。",
    icon: SplitSquareHorizontal,
    path: ["download_threads"],
    type: "number",
    min: 1,
    max: 16,
    defaultValue: 4,
    unit: "片",
    keywords: "加速 提速 线程 threads",
  },
  {
    id: "download_connections",
    page: "download",
    tab: "performance",
    section: "concurrency",
    title: "每个数据中心连接数",
    desc: "所有下载共享的到 Telegram 媒体服务器的连接数，分片会轮流分配到这些连接上。",
    icon: Network,
    path: ["download_connections"],
    type: "number",
    min: 1,
    max: 16,
    defaultValue: 2,
    unit: "条",
    keywords: "加速 提速 连接 connections",
  },
  {
    id: "download_max_in_flight",
    page: "download",
    tab: "performance",
    section: "concurrency",
    title: "同时请求的分片上限",
    desc: "所有文件合计同时向同一数据中心请求的分片数。实测超过 16 左右时 Telegram 会停止响应、速度掉到 0，8 已能跑满线路。",
    icon: Gauge,
    path: ["download_max_in_flight"],
    type: "number",
    min: 1,
    max: 32,
    defaultValue: 8,
    unit: "片",
    keywords: "加速 提速 并发 限流 in flight",
  },
  {
    id: "max_concurrent_transmissions",
    page: "download",
    tab: "performance",
    section: "concurrency",
    title: "最大并发传输",
    desc: "底层连接的并发分片数，留空时为同时下载数 × 5。",
    icon: CircleGauge,
    path: ["max_concurrent_transmissions"],
    type: "number",
    min: 1,
    max: 200,
    placeholder: "自动",
    unit: "路",
  },
  {
    id: "scan_prefetch_limit",
    page: "download",
    tab: "performance",
    section: "concurrency",
    title: "扫描预取上限",
    desc: "扫描消息最多领先下载的数量，避免一次性排入大量任务。0 表示不限制，-1 表示与同时下载数相同。",
    icon: ScanSearch,
    path: ["scan_prefetch_limit"],
    type: "number",
    min: -1,
    max: 1000,
    defaultValue: 5,
    unit: "条",
  },
  {
    id: "download_stall_timeout",
    page: "download",
    tab: "performance",
    section: "retry",
    title: "下载停滞超时",
    desc: "超过该时间没有收到新数据时，重新建立下载并从断点续传。",
    icon: AlarmClock,
    path: ["download_stall_timeout"],
    type: "number",
    min: 10,
    max: 3600,
    defaultValue: 90,
    unit: "秒",
  },
  {
    id: "history_fetch_timeout",
    page: "download",
    tab: "performance",
    section: "retry",
    title: "消息扫描超时",
    desc: "单次获取频道历史消息的超时时间。",
    icon: Timer,
    path: ["history_fetch_timeout"],
    type: "number",
    min: 5,
    max: 600,
    defaultValue: 60,
    unit: "秒",
  },
  {
    id: "history_fetch_retries",
    page: "download",
    tab: "performance",
    section: "retry",
    title: "消息扫描重试",
    desc: "获取历史消息失败后的重试次数。",
    icon: Repeat,
    path: ["history_fetch_retries"],
    type: "number",
    min: 1,
    max: 20,
    defaultValue: 3,
    unit: "次",
  },
  {
    id: "start_timeout",
    page: "download",
    tab: "performance",
    section: "retry",
    title: "连接超时",
    desc: "启动时连接 Telegram 的最长等待时间。",
    icon: Wifi,
    path: ["start_timeout"],
    type: "number",
    min: 10,
    max: 600,
    defaultValue: 60,
    unit: "秒",
  },

  // ------------------------------------------------------------ network / account
  {
    id: "api_id",
    page: "network",
    tab: "account",
    section: "telegram",
    title: "API ID",
    desc: "在 my.telegram.org → API development tools 中获取。",
    icon: Hash,
    path: ["api_id"],
    type: "text",
    width: 220,
    placeholder: "1234567",
    keywords: "api_id 登录",
  },
  {
    id: "api_hash",
    page: "network",
    tab: "account",
    section: "telegram",
    title: "API Hash",
    desc: "与 API ID 配对的 32 位密钥，请勿泄露。",
    icon: KeyRound,
    path: ["api_hash"],
    type: "password",
    width: 300,
  },
  {
    id: "language",
    page: "network",
    tab: "account",
    section: "telegram",
    title: "引擎语言",
    desc: "日志与机器人消息使用的语言。",
    icon: Languages,
    path: ["language"],
    type: "select",
    defaultValue: "ZH",
    options: [
      { label: "简体中文", value: "ZH" },
      { label: "English", value: "EN" },
      { label: "Русский", value: "RU" },
      { label: "Українська", value: "UA" },
    ],
  },
  {
    id: "bot_token",
    page: "network",
    tab: "account",
    section: "bot",
    title: "机器人 Token",
    desc: "从 @BotFather 获取。填写后可在 Telegram 中用 /download 下发任务并接收进度通知。",
    icon: Bot,
    path: ["bot_token"],
    type: "password",
    width: 300,
    placeholder: "可选",
  },
  {
    id: "allowed_user_ids",
    page: "network",
    tab: "account",
    section: "bot",
    title: "允许使用机器人的用户",
    desc: "填写用户 ID 或 @用户名；me 表示当前登录的账号。",
    icon: AtSign,
    path: ["allowed_user_ids"],
    type: "tags",
    placeholder: "me、@name、12345…",
    defaultValue: ["me"],
  },

  // ------------------------------------------------------------ network / proxy
  {
    id: "proxy.enabled",
    page: "network",
    tab: "proxy",
    section: "proxy",
    title: "使用代理连接 Telegram",
    desc: "开启后通过下方的代理服务器连接 Telegram。",
    icon: Plug,
    path: ["proxy"],
    type: "optional-switch",
    enableValue: { scheme: "socks5", hostname: "127.0.0.1", port: 7890 },
  },
  {
    id: "proxy.scheme",
    page: "network",
    tab: "proxy",
    section: "proxy",
    title: "协议",
    desc: "代理服务器类型。",
    icon: Network,
    path: ["proxy", "scheme"],
    type: "segmented",
    showIf: ["proxy"],
    options: [
      { label: "SOCKS5", value: "socks5" },
      { label: "SOCKS4", value: "socks4" },
      { label: "HTTP", value: "http" },
    ],
  },
  {
    id: "proxy.hostname",
    page: "network",
    tab: "proxy",
    section: "proxy",
    title: "地址",
    desc: "代理服务器的主机名或 IP。",
    icon: Server,
    path: ["proxy", "hostname"],
    type: "text",
    width: 220,
    showIf: ["proxy"],
  },
  {
    id: "proxy.port",
    page: "network",
    tab: "proxy",
    section: "proxy",
    title: "端口",
    desc: "代理服务器端口，Clash 默认混合端口为 7890。",
    icon: Hash,
    path: ["proxy", "port"],
    type: "number",
    min: 1,
    max: 65535,
    showIf: ["proxy"],
  },
  {
    id: "proxy.username",
    page: "network",
    tab: "proxy",
    section: "proxy",
    title: "用户名",
    desc: "无需认证时留空。",
    icon: User,
    path: ["proxy", "username"],
    type: "text",
    width: 220,
    placeholder: "可选",
    showIf: ["proxy"],
  },
  {
    id: "proxy.password",
    page: "network",
    tab: "proxy",
    section: "proxy",
    title: "密码",
    desc: "无需认证时留空。",
    icon: Lock,
    path: ["proxy", "password"],
    type: "password",
    width: 220,
    placeholder: "可选",
    showIf: ["proxy"],
  },

  // ------------------------------------------------------------ network / clash
  {
    id: "clash.enabled",
    page: "network",
    tab: "clash",
    section: "clash",
    title: "低速时自动切换节点",
    desc: "下载速度持续过低或 Telegram 请求失败时，通过 Clash 控制器切换到延迟最低的可用节点。",
    icon: Zap,
    path: ["clash", "enabled"],
    type: "switch",
    defaultValue: true,
  },
  {
    id: "clash.controller",
    page: "network",
    tab: "clash",
    section: "clash",
    title: "控制器地址",
    desc: "Clash / mihomo 的 external-controller，例如 http://127.0.0.1:9097。",
    icon: Link2,
    path: ["clash", "controller"],
    type: "text",
    width: 260,
    defaultValue: "http://127.0.0.1:9097",
  },
  {
    id: "clash.secret",
    page: "network",
    tab: "clash",
    section: "clash",
    title: "控制器密钥",
    desc: "external-controller 的 secret，未设置时留空。",
    icon: Shield,
    path: ["clash", "secret"],
    type: "password",
    width: 220,
  },
  {
    id: "clash.selector",
    page: "network",
    tab: "clash",
    section: "clash",
    title: "策略组",
    desc: "要切换的 Selector 策略组名称，留空时自动选择。",
    icon: SlidersHorizontal,
    path: ["clash", "selector"],
    type: "text",
    width: 220,
    placeholder: "自动",
  },
  {
    id: "clash.low_speed_kb",
    page: "network",
    tab: "clash",
    section: "clash",
    title: "低速阈值",
    desc: "总下载速度低于此值视为低速。",
    icon: Gauge,
    path: ["clash", "low_speed_kb"],
    type: "number",
    min: 1,
    max: 100000,
    defaultValue: 100,
    unit: "KB/s",
  },
  {
    id: "clash.low_speed_seconds",
    page: "network",
    tab: "clash",
    section: "clash",
    title: "低速持续时间",
    desc: "低速持续超过该时间才切换节点。",
    icon: Timer,
    path: ["clash", "low_speed_seconds"],
    type: "number",
    min: 5,
    max: 3600,
    defaultValue: 60,
    unit: "秒",
  },
  {
    id: "clash.switch_cooldown_seconds",
    page: "network",
    tab: "clash",
    section: "clash",
    title: "切换冷却",
    desc: "两次切换之间的最短间隔。",
    icon: AlarmClock,
    path: ["clash", "switch_cooldown_seconds"],
    type: "number",
    min: 10,
    max: 86400,
    defaultValue: 300,
    unit: "秒",
  },
  {
    id: "clash.timeout_ms",
    page: "network",
    tab: "clash",
    section: "clash",
    title: "测速超时",
    desc: "测试单个节点延迟的超时时间。",
    icon: Timer,
    path: ["clash", "timeout_ms"],
    type: "number",
    min: 500,
    max: 30000,
    step: 500,
    defaultValue: 5000,
    unit: "毫秒",
  },
  {
    id: "clash.test_url",
    page: "network",
    tab: "clash",
    section: "clash",
    title: "测速地址",
    desc: "用于测试节点延迟的 URL。",
    icon: Globe,
    path: ["clash", "test_url"],
    type: "text",
    width: 300,
    defaultValue: "https://www.gstatic.com/generate_204",
  },

  // ------------------------------------------------------------ upload
  {
    id: "upload_drive.enable_upload_file",
    page: "upload",
    tab: "drive",
    section: "drive",
    title: "下载后上传到网盘",
    desc: "每个文件下载完成后自动上传。",
    icon: CloudUpload,
    path: ["upload_drive", "enable_upload_file"],
    type: "switch",
    defaultValue: false,
  },
  {
    id: "upload_drive.upload_adapter",
    page: "upload",
    tab: "drive",
    section: "drive",
    title: "上传方式",
    desc: "rclone 支持几乎所有网盘；aligo 用于阿里云盘。",
    icon: Plug,
    path: ["upload_drive", "upload_adapter"],
    type: "segmented",
    defaultValue: "rclone",
    options: [
      { label: "rclone", value: "rclone" },
      { label: "aligo", value: "aligo" },
    ],
  },
  {
    id: "upload_drive.rclone_path",
    page: "upload",
    tab: "drive",
    section: "drive",
    title: "rclone 程序",
    desc: "rclone.exe 的完整路径。",
    icon: Terminal,
    path: ["upload_drive", "rclone_path"],
    type: "file",
  },
  {
    id: "upload_drive.remote_dir",
    page: "upload",
    tab: "drive",
    section: "drive",
    title: "远程目录",
    desc: "上传目标，例如 drive:/telegram。",
    icon: Folder,
    path: ["upload_drive", "remote_dir"],
    type: "text",
    width: 260,
    placeholder: "drive:/telegram",
  },
  {
    id: "upload_drive.before_upload_file_zip",
    page: "upload",
    tab: "drive",
    section: "drive",
    title: "上传前压缩",
    desc: "将文件压缩为 zip 后再上传。",
    icon: FileArchive,
    path: ["upload_drive", "before_upload_file_zip"],
    type: "switch",
    defaultValue: false,
  },
  {
    id: "upload_drive.after_upload_file_delete",
    page: "upload",
    tab: "drive",
    section: "drive",
    title: "上传后删除本地文件",
    desc: "确认上传成功后才会删除。",
    icon: Trash2,
    path: ["upload_drive", "after_upload_file_delete"],
    type: "switch",
    defaultValue: false,
  },
  {
    id: "after_upload_telegram_delete",
    page: "upload",
    tab: "forward",
    section: "forward",
    title: "转发后删除本地文件",
    desc: "媒体转发到目标频道后，删除本地下载的文件。",
    icon: Trash2,
    path: ["after_upload_telegram_delete"],
    type: "switch",
    defaultValue: true,
  },
  {
    id: "forward_limit",
    page: "upload",
    tab: "forward",
    section: "forward",
    title: "每分钟转发上限",
    desc: "避免触发 Telegram 频率限制，一般无需修改。",
    icon: Gauge,
    path: ["forward_limit"],
    type: "number",
    min: 1,
    max: 200,
    defaultValue: 33,
    unit: "条",
  },

  // ------------------------------------------------------------ settings / general (desktop)
  {
    id: "theme",
    page: "settings",
    tab: "general",
    section: "appearance",
    title: "主题",
    desc: "跟随系统，或固定浅色 / 深色。",
    icon: Palette,
    path: ["theme"],
    type: "segmented",
    desktop: true,
    options: [
      { label: "跟随系统", value: "system" },
      { label: "浅色", value: "light" },
      { label: "深色", value: "dark" },
    ],
  },
  {
    id: "closeToTray",
    page: "settings",
    tab: "general",
    section: "appearance",
    title: "关闭窗口时最小化到托盘",
    desc: "关闭主窗口后引擎继续在后台下载。",
    icon: AppWindow,
    path: ["closeToTray"],
    type: "switch",
    desktop: true,
  },
  {
    id: "autostart",
    page: "settings",
    tab: "general",
    section: "startup",
    title: "开机自启动",
    desc: "登录 Windows 后自动打开 TDL Desktop。",
    icon: Power,
    path: ["__autostart"],
    type: "switch",
    desktop: true,
  },
  {
    id: "startHidden",
    page: "settings",
    tab: "general",
    section: "startup",
    title: "开机启动时隐藏到托盘",
    desc: "开机自启动时不弹出主窗口，只在托盘中运行；单击托盘图标可打开面板。",
    icon: AppWindow,
    path: ["startHidden"],
    type: "switch",
    desktop: true,
    keywords: "静默 最小化 后台",
  },
  {
    id: "autoStartEngine",
    page: "settings",
    tab: "general",
    section: "startup",
    title: "启动时运行引擎",
    desc: "打开 TDL Desktop 后自动启动下载引擎，并恢复未完成的任务。",
    icon: Zap,
    path: ["autoStartEngine"],
    type: "switch",
    desktop: true,
  },
  {
    id: "scheduleEnabled",
    page: "settings",
    tab: "general",
    section: "guard",
    title: "按时间段下载",
    desc: "只在指定时间段内下载，其余时间自动暂停。手动点击“继续下载”后保持到下一次时段切换。",
    icon: CalendarClock,
    path: ["scheduleEnabled"],
    type: "switch",
    desktop: true,
    keywords: "计划 定时 夜间",
  },
  {
    id: "scheduleStart",
    page: "settings",
    tab: "general",
    section: "guard",
    title: "开始时间",
    desc: "每天从这个时间开始下载。",
    icon: Clock,
    path: ["scheduleStart"],
    type: "time",
    desktop: true,
  },
  {
    id: "scheduleEnd",
    page: "settings",
    tab: "general",
    section: "guard",
    title: "结束时间",
    desc: "到这个时间自动暂停；早于开始时间表示跨越午夜，例如 22:00 – 07:00。",
    icon: Clock,
    path: ["scheduleEnd"],
    type: "time",
    desktop: true,
  },
  {
    id: "minFreeGb",
    page: "settings",
    tab: "general",
    section: "guard",
    title: "磁盘空间保护",
    desc: "下载磁盘剩余空间低于该值时自动暂停，空间恢复后自动继续。0 表示关闭。",
    icon: HardDrive,
    path: ["minFreeGb"],
    type: "number",
    desktop: true,
    min: 0,
    max: 100000,
    unit: "GB",
    keywords: "空间 磁盘 保护",
  },
  {
    id: "notifyTaskFinished",
    page: "settings",
    tab: "general",
    section: "notify",
    title: "任务完成",
    desc: "一个下载任务全部完成时发送系统通知。",
    icon: Bell,
    path: ["notifyTaskFinished"],
    type: "switch",
    desktop: true,
  },
  {
    id: "notifyLoginRequired",
    page: "settings",
    tab: "general",
    section: "notify",
    title: "需要登录",
    desc: "引擎等待输入手机号、验证码或密码时提醒。",
    icon: KeyRound,
    path: ["notifyLoginRequired"],
    type: "switch",
    desktop: true,
  },
  {
    id: "notifyEngineError",
    page: "settings",
    tab: "general",
    section: "notify",
    title: "引擎异常退出",
    desc: "引擎意外停止时提醒。",
    icon: Shield,
    path: ["notifyEngineError"],
    type: "switch",
    desktop: true,
  },
  {
    id: "pollInterval",
    page: "settings",
    tab: "general",
    section: "appearance",
    title: "仪表盘刷新间隔",
    desc: "读取引擎实时状态的频率。",
    icon: Activity,
    path: ["pollInterval"],
    type: "number",
    desktop: true,
    min: 1,
    max: 10,
    unit: "秒",
  },

  // ------------------------------------------------------------ settings / engine
  {
    id: "workspace",
    page: "settings",
    tab: "engine",
    section: "engineRuntime",
    title: "工作目录",
    desc: "存放 config.yaml、登录会话、临时文件与日志。可以直接选择旧版 tdl.exe 所在的文件夹继续使用。",
    icon: Folder,
    path: ["workspace"],
    type: "path",
    desktop: true,
    placeholder: "自动",
    keywords: "workspace 数据目录",
  },
  {
    id: "enginePath",
    page: "settings",
    tab: "engine",
    section: "engineRuntime",
    title: "引擎程序",
    desc: "留空使用内置引擎；也可指定其他版本的 tdl.exe 或 media_downloader.py。",
    icon: MonitorCog,
    path: ["enginePath"],
    type: "file",
    desktop: true,
    placeholder: "内置引擎",
  },
  {
    id: "pythonPath",
    page: "settings",
    tab: "engine",
    section: "engineRuntime",
    title: "Python 解释器",
    desc: "引擎程序为 .py 脚本时使用，留空则使用 PATH 中的 python。",
    icon: Terminal,
    path: ["pythonPath"],
    type: "file",
    desktop: true,
    placeholder: "python",
  },
  {
    id: "log_level",
    page: "settings",
    tab: "engine",
    section: "engineLog",
    title: "日志级别",
    desc: "写入 log/tdl.log 的最低级别。",
    icon: FileClock,
    path: ["log_level"],
    type: "segmented",
    defaultValue: "INFO",
    options: [
      { label: "DEBUG", value: "DEBUG" },
      { label: "INFO", value: "INFO" },
      { label: "WARNING", value: "WARNING" },
      { label: "ERROR", value: "ERROR" },
    ],
  },
  {
    id: "web_host",
    page: "settings",
    tab: "engine",
    section: "web",
    title: "监听地址",
    desc: "127.0.0.1 仅本机可访问；0.0.0.0 允许局域网访问 Web 页面。",
    icon: Server,
    path: ["web_host"],
    type: "select",
    defaultValue: "0.0.0.0",
    options: [
      { label: "仅本机（127.0.0.1）", value: "127.0.0.1" },
      { label: "局域网（0.0.0.0）", value: "0.0.0.0" },
    ],
  },
  {
    id: "web_port",
    page: "settings",
    tab: "engine",
    section: "web",
    title: "端口",
    desc: "Web 页面与桌面端通信使用的端口，被占用时会自动改用空闲端口。",
    icon: Hash,
    path: ["web_port"],
    type: "number",
    min: 1,
    max: 65535,
    defaultValue: 5000,
  },
  {
    id: "web_login_secret",
    page: "settings",
    tab: "engine",
    section: "web",
    title: "访问密码",
    desc: "Web 页面登录密码，留空则无需登录。",
    icon: Lock,
    path: ["web_login_secret"],
    type: "password",
    width: 220,
    placeholder: "不设置",
  },
];

export function settingsFor(page: PageId, tab?: string): SettingDef[] {
  return SETTINGS.filter((s) => s.page === page && (!tab || s.tab === tab));
}

export function pageDef(page: PageId): PageDef {
  return PAGES.find((p) => p.id === page)!;
}

/** Extra searchable entries for custom (non-schema) panels. */
export const EXTRA_SEARCH: { id: string; page: PageId; tab: string; title: string; desc: string; icon: LucideIcon }[] = [
  { id: "chat-list", page: "chats", tab: "list", title: "下载频道", desc: "添加要下载的频道、起始消息与过滤条件", icon: Users },
  { id: "download_filter", page: "chats", tab: "list", title: "下载过滤表达式", desc: "按日期、大小、类型等条件过滤消息", icon: SlidersHorizontal },
  { id: "filter_advertisement_list", page: "chats", tab: "ads", title: "广告关键词过滤", desc: "包含这些关键词的消息不会被转发", icon: Shield },
  { id: "clash-panel", page: "network", tab: "clash", title: "节点测速与切换", desc: "查看 Clash 策略组、测速并手动切换节点", icon: Zap },
  { id: "sessions", page: "network", tab: "account", title: "登录会话", desc: "查看或退出当前 Telegram 登录", icon: User },
  { id: "new-task", page: "tasks", tab: "new", title: "新建下载任务", desc: "输入频道链接与消息范围开始下载", icon: Download },
  { id: "storage", page: "settings", tab: "data", title: "存储与临时文件", desc: "磁盘空间、临时文件清理", icon: HardDrive },
  { id: "backups", page: "settings", tab: "data", title: "配置备份", desc: "每次保存前自动备份，可一键恢复", icon: FileClock },
  { id: "raw-config", page: "settings", tab: "advanced", title: "编辑 config.yaml 源码", desc: "直接编辑配置文件", icon: FileText },
];
